-- See https://github.com/Akashortstack/Psychonauts_AP/blob/main/Locations.py for IDs
LOCATION_MAPPING = {
    -- CASA
    [1] = "@CASA/(CA Lab) Behind Furniture/",
    [2] = "@CASA/(CA Lab) Staircase Ledges/",
    [3] = "@CASA/(CA Lab) Upper Ledge/",

    -- CAGP
    [4] = "@CAGP/(CA GPC) Top of GPC/",
    [5] = "@CAGP/(CA GPC) Under GPC/",
    [6] = "@CAGP/(CA GPC) Mountain Lion Log Bridge/",
    [7] = "@CAGP/(CA GPC) Above Entrance to Lake/",
    [8] = "@CAGP/(CA GPC) Rock Wall Behind Tree/",
    [9] = "@CAGP/(CA GPC) Rock Wall Top/",
    [10] = "@CAGP/(CA GPC) Tree Near Fence/",
    [11] = "@CAGP/(CA GPC) Tree Near Geyser/",
    [12] = "@CAGP/(CA GPC) Fence Behind GPC/",
    [13] = "@CAGP/(CA GPC) Near the Bear/",
    [14] = "@CAGP/(CA GPC) Rocky Platforms Behind GPC Right/",
    [15] = "@CAGP/(CA GPC) Rocky Platforms Behind GPC Left/",
    [16] = "@CAGP/(CA GPC) Top of Log Flume/",
    [17] = "@CAGP/(CA GPC) Ride the Log Flume/",
    [18] = "@CAGP/(CA GPC) Bottom of Log Flume/",
    [19] = "@CAGP/(CA GPC) Big Rock Near Ford/",
    [20] = "@CAGP/(CA GPC) Inside the Ruined Cabin/",
    [21] = "@CAGP/(CA GPC) Branch Swinging Course Start/",
    [22] = "@CAGP/(CA GPC) Branch Swinging Course Mid/",
    [23] = "@CAGP/(CA GPC) Branch Swinging Course End/",
    [24] = "@CAGP/(CA GPC) Branch Above Squirrel/",
    [25] = "@CAGP/(CA GPC) Creek Grate/",
    [26] = "@CAGPSquirrel/(CA GPC) Squirrel's Acorn/",
    [27] = "@CAGPGeyser/(CA GPC) Wedged in the Geyser/",

    -- CAGP Deep Arrowheads
    [512] = "@CAGPDeepAH/(CA GPC Deep AH) In River Before Grate/",
    [513] = "@CAGPDeepAH/(CA GPC Deep AH) Inside GPC Fence North/",
    [514] = "@CAGPDeepAH/(CA GPC Deep AH) Near Stump/",
    [515] = "@CAGPDeepAH/(CA GPC Deep AH) Near Squirrel/",
    [516] = "@CAGPDeepAH/(CA GPC Deep AH) In River Near Ruined Cabin/",
    [517] = "@CAGPDeepAH/(CA GPC Deep AH) Inside GPC Fence South West/",
    [518] = "@CAGPDeepAH/(CA GPC Deep AH) Larger Rock by Lake Entrance/",
    [519] = "@CAGPDeepAH/(CA GPC Deep AH) Near Geyser/",
    [520] = "@CAGPDeepAH/(CA GPC Deep AH) Near Bear/",
    [521] = "@CAGPDeepAH/(CA GPC Deep AH) Big Rock Near Ford/",
    [522] = "@CAGPDeepAH/(CA GPC Deep AH) Opposite River From Stump/",
    [523] = "@CAGPDeepAH/(CA GPC Deep AH) Before Entrance to Camp/",
    [524] = "@CAGPDeepAH/(CA GPC Deep AH) Before Entrance to Lake/",
    [525] = "@CAGPDeepAH/(CA GPC Deep AH) Smaller Rock by Lake Entrance/",
    [526] = "@CAGPDeepAH/(CA GPC Deep AH) Inside GPC Fence South East/",

    -- CAMA
    [28] = "@CAMA/(CA Main) Fence Near Kids' Cabins/",
    [29] = "@CAMA/(CA Main) Under Lodge Front Steps/",
    [30] = "@CAMA/(CA Main) Behind Tree Near Lodge/",
    [31] = "@CAMA/(CA Main) Under the Lodge/",
    [32] = "@CAMA/(CA Main) Loudspeaker 1 Platform/",
    [33] = "@CAMA/(CA Main) Under Lodge Metal Roof/",
    [34] = "@CAMA/(CA Main) Loudspeaker Tightrope Walk/",
    [35] = "@CAMA/(CA Main) Loudspeaker 2 Platform/",
    [36] = "@CAMA/(CA Main) Lodge Roof/",
    [37] = "@CAMA/(CA Main) Metal Roof Outcropping/",
    [38] = "@CAMA/(CA Main) Loudspeaker Above Stump/",
    [39] = "@CAMA/Tree Platform/(CA Main) Tree Platform Left",
    [40] = "@CAMA/Tree Platform/(CA Main) Tree Platform Right",
    [41] = "@CAMA/(CA Main) Rock Wall Top/",
    [42] = "@CAMA/(CA Main) Parking Lot Arch/",
    [43] = "@CAMA/(CA Main) Parking Lot Small Log/",
    [44] = "@CAMA/(CA Main) Oleander's Car/",
    [45] = "@CAMA/(CA Main) Parking Lot Basketball Hoop/",
    [46] = "@CAMALev/(CA Main) Parking Lot History Board/",
    [47] = "@CAMA/(CA Main) Parking Lot Outhouse/",
    [48] = "@CAMA/(CA Main) Rock Near Bench/",

    -- CAMA Deep Arrowheads
    [503] = "@CAMADeepAH/(CA Main Deep AH) Trash Can North of Lodge/",
    [504] = "@CAMADeepAH/(CA Main Deep AH) Lodge Front Steps Corner/",
    [505] = "@CAMADeepAH/(CA Main Deep AH) Under Lake Bridge/",
    [506] = "@CAMADeepAH/(CA Main Deep AH) GPC Path Before Cougar/",
    [507] = "@CAMADeepAH/(CA Main Deep AH) West of Stump/",
    [508] = "@CAMADeepAH/(CA Main Deep AH) Reception Entrance/",
    [509] = "@CAMADeepAH/(CA Main Deep AH) Parking Lot Log Fence/",
    [510] = "@CAMADeepAH/(CA Main Deep AH) Under the Lodge/",
    [511] = "@CAMADeepAH/(CA Main Deep AH) Rock Wall Top/",

    -- CAKC
    [49] = "@CAKC/(CA Cabins) Grinding on the Roots/",
    [50] = "@CAKC/(CA Cabins) Under Stairs/",
    [51] = "@CAKC/(CA Cabins) Top of Loudspeaker/",
    [52] = "@CAKC/(CA Cabins) Cabin Roof 1/",
    [53] = "@CAKC/(CA Cabins) Trampoline Above Outhouse/",
    [54] = "@CAKC/(CA Cabins) Trampoline Platform/",
    [55] = "@CAKC/(CA Cabins) Cabins Outhouse/",
    [56] = "@CAKC/(CA Cabins) Behind Cabin/",
    [57] = "@CAKC/(CA Cabins) Roof of Cabin 2/",
    [58] = "@CAKC/(CA Cabins) Cave Entrance/",
    [59] = "@CAKC/(CA Cabins) Deep Cave Path/",
    [60] = "@CAKC/(CA Cabins) Deep Cave Ladder/",
    [61] = "@CAKCLev/(CA Cabins) High-Up Tightrope/",
    [62] = "@CAKCPyro/(CA Cabins) Cave Refrigerator/",

    -- CARE
    [63] = "@CARE/(CA Reception) Graveyard Bear/",
    [64] = "@CARE/(CA Reception) Near Beehive/",
    [65] = "@CARE/(CA Reception) Mineshaft Trailer Entrance/",
    [66] = "@CARE/(CA Reception) Tightrope Start/",
    [67] = "@CARE/(CA Reception) Tightrope End/",
    [68] = "@CARE/(CA Reception) Rocks Near Trailer/",
    [69] = "@CARELev_optional/(CA Reception) Fireplace Tree Lower/",
    [70] = "@CARE/(CA Reception) Fireplace Tree Rock/",
    [71] = "@CARELev/(CA Reception) Swamp Skinny Poles/",
    [72] = "@CARE/(CA Reception) Big Log Platform/",
    [73] = "@CARE/(CA Reception) Above Waterfall Left/",
    [74] = "@CARE/(CA Reception) Above Waterfall Right/",
    [75] = "@CARE/(CA Reception) Behind the Waterfall/",
    [76] = "@CARE/(CA Reception) Weird Tree Left/",
    [77] = "@CARE/(CA Reception) Weird Tree Right/",
    [78] = "@CARE/(CA Reception) Log Hill Top/",
    [79] = "@CARE/(CA Reception) Log Hill Behind/",
    [80] = "@CARE/(CA Reception) Mineshaft Grind Rail/",
    [81] = "@CARE/Mineshaft Upper Entrance/(CA Reception) Mineshaft Upper Entrance",
    [82] = "@CARE/Mineshaft Upper Entrance/(CA Reception) Mineshaft Above Upper Entrance",
    [83] = "@CARE/(CA Reception) Inside Mineshaft/",
    [84] = "@CARE/(CA Reception) Mineshaft Bear/",
    [85] = "@CARE/(CA Reception) Swamp Bird's Nest/",
    [86] = "@CARE/(CA Reception) Collapsed Cave/",
    [87] = "@CARELev/(CA Reception) Fireplace Tree Top/",
    [88] = "@CAREMark/(CA Reception) Hornet Nest/",

    -- CARE Deep Arrowheads
    [527] = "@CAREDeepAH/(CA Reception Deep AH) Mineshaft Bear/",
    [528] = "@CAREDeepAH/(CA Reception Deep AH) Shallow Water East/",
    [529] = "@CAREDeepAH/(CA Reception Deep AH) Shallow Water West/",
    [530] = "@CAREDeepAH/(CA Reception Deep AH) Collapsed Cave/",
    [531] = "@CAREDeepAH/(CA Reception Deep AH) Fireplace Tree/",
    [532] = "@CAREDeepAH/(CA Reception Deep AH) South of Trailer/",
    [533] = "@CAREDeepAH/(CA Reception Deep AH) East of Trailer/",
    [534] = "@CAREDeepAH/(CA Reception Deep AH) Graveyard Tree/",
    [535] = "@CAREDeepAH/(CA Reception Deep AH) In Front of Graveyard/",
    [536] = "@CAREDeepAH/(CA Reception Deep AH) Graveyard Corner/",
    [537] = "@CAREDeepAH/(CA Reception Deep AH) West of Campfire/",
    [538] = "@CAREDeepAH/(CA Reception Deep AH) North East of Campfire/",
    [539] = "@CAREDeepAH/(CA Reception Deep AH) Mineshaft Lower Entrance/",
    [540] = "@CAREDeepAH/(CA Reception Deep AH) By Stump/",
    [541] = "@CAREDeepAH/(CA Reception Deep AH) Waterfall River Split/",
    [542] = "@CAREDeepAH/(CA Reception Deep AH) Log Hill Lower/",
    [543] = "@CAREDeepAH/(CA Reception Deep AH) Log Hill Top/",
    [544] = "@CAREDeepAH/(CA Reception Deep AH) Below Tightrope Platform/",

    -- CABH
    [89] = "@CABH/(CA Lake) Under the First Bridge/",
    [90] = "@CABH/(CA Lake) Behind Stump/",
    [91] = "@CABH/(CA Lake) Left of Entrance Rock Wall/",
    [92] = "@CABH/(CA Lake) Poles on Lake/",
    [93] = "@CABH/Bathysphere/(CA Lake) Bathysphere Roof",
    [94] = "@CABH/(CA Lake) Bathysphere Dock/",
    [95] = "@CABH/(CA Lake) Metal Roof Above Docks/",
    [96] = "@CABH/(CA Lake) Above Ford Ropes/",
    [97] = "@CABH/(CA Lake) Above Ford Cabin Platform/",
    [98] = "@CABH/(CA Lake) Outside Cougar Cave/",
    [99] = "@CABH/(CA Lake) Inside Cougar Cave/",
    [100] = "@CABH/(CA Lake) Bulletin Board Bushes/",
    [101] = "@CABH/Pink Tree Platform/(CA Lake) Pink Trees Platform Left",
    [102] = "@CABH/Pink Tree Platform/(CA Lake) Pink Trees Platform Right",
    [103] = "@CABH/(CA Lake) Rock Wall Upper/",
    [104] = "@CABH/(CA Lake) Lake Shore/",
    [105] = "@CABH/(CA Lake) Tiny Island/",
    [106] = "@CABHLev/(CA Lake) Top of Big Rock/",
    [107] = "@CABH/(CA Lake) Rock Wall Gap/",
    [345] = "@CABH/Bathysphere/(CA Lake) Lungfish Boss Complete",

    -- CABH Deep Arrowheads
    [545] = "@CABHDeepAH/(CA Lake Deep AH) By Stump/",
    [546] = "@CABHDeepAH/(CA Lake Deep AH) Lake Shore/",
    [547] = "@CABHDeepAH/(CA Lake Deep AH) Bathysphere Rock/",
    [548] = "@CABHDeepAH/(CA Lake Deep AH) GPC Tunnel Entrance/",
    [549] = "@CABHDeepAH/(CA Lake Deep AH) Rock Wall Upper/",
    [550] = "@CABHDeepAH/(CA Lake Deep AH) Boathouse Entrance/",
    [551] = "@CABHDeepAH/(CA Lake Deep AH) Right of Entrance/",

    -- CALI
    [108] = "@CALI/Main Lodge Interior/(CA Lodge) Main Lodge Rafters",

    -- CAJA
    [109] = "@CAJA/(CA Ford) Top of Sanctuary/",
    [110] = "@CAJA/(CA Ford) Bottom of Sanctuary/",

    -- Rank
    [606] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 02",
    [607] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 03",
    [608] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 04",
    [609] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 05",
    [610] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 06",
    [611] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 07",
    [612] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 08",
    [613] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 09",
    [614] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 10",
    [615] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 11",
    [616] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 12",
    [617] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 13",
    [618] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 14",
    [619] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 15",
    [620] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 16",
    [621] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 17",
    [622] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 18",
    [623] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 19",
    [624] = "@RANK2to20/Ranks 2 to 20/(Rank Up) PSI Rank 20",
    [625] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 21",
    [626] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 22",
    [627] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 23",
    [628] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 24",
    [629] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 25",
    [630] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 26",
    [631] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 27",
    [632] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 28",
    [633] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 29",
    [634] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 30",
    [635] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 31",
    [636] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 32",
    [637] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 33",
    [638] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 34",
    [639] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 35",
    [640] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 36",
    [641] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 37",
    [642] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 38",
    [643] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 39",
    [644] = "@RANK21to40/Ranks 21 to 40/(Rank Up) PSI Rank 40",
    [645] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 41",
    [646] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 42",
    [647] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 43",
    [648] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 44",
    [649] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 45",
    [650] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 46",
    [651] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 47",
    [652] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 48",
    [653] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 49",
    [654] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 50",
    [655] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 51",
    [656] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 52",
    [657] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 53",
    [658] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 54",
    [659] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 55",
    [660] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 56",
    [661] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 57",
    [662] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 58",
    [663] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 59",
    [664] = "@RANK41to60/Ranks 41 to 60/(Rank Up) PSI Rank 60",
    [665] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 61",
    [666] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 62",
    [667] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 63",
    [668] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 64",
    [669] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 65",
    [670] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 66",
    [671] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 67",
    [672] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 68",
    [673] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 69",
    [674] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 70",
    [675] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 71",
    [676] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 72",
    [677] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 73",
    [678] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 74",
    [679] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 75",
    [680] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 76",
    [681] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 77",
    [682] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 78",
    [683] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 79",
    [684] = "@RANK61to80/Ranks 61 to 80/(Rank Up) PSI Rank 80",
    [685] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 81",
    [686] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 82",
    [687] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 83",
    [688] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 84",
    [689] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 85",
    [690] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 86",
    [691] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 87",
    [692] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 88",
    [693] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 89",
    [694] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 90",
    [695] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 91",
    [696] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 92",
    [697] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 93",
    [698] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 94",
    [699] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 95",
    [700] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 96",
    [701] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 97",
    [702] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 98",
    [703] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 99",
    [704] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 100",
    [705] = "@RANK81to101/Ranks 81 to 101/(Rank Up) PSI Rank 101",

    -- ASGR
    [111] = "@ASGR/(AS Grounds) Rock Wall Bottom/",
    [112] = "@ASGR/(AS Grounds) Rock Wall Ladder/",
    [113] = "@ASGRLev/(AS Grounds) Outside Front Gate/",
    [114] = "@ASGRLev/(AS Grounds) Pillar Above Gate/",
    [115] = "@ASGR/(AS Grounds) Fountain Top/",
    [116] = "@ASGR/(AS Grounds) Hedge Alcove/",
    [117] = "@ASGR/(AS Grounds) Asylum Doors Right/",
    [118] = "@ASGR/(AS Grounds) Asylum Doors Left/",
    [119] = "@ASGR/(AS Grounds) Corner Near Fence/",
    [120] = "@ASGR/(AS Grounds) Ledge Before Gloria/",

    -- ASCO
    [121] = "@ASCO/(AS Courtyard) Above Elevator/",
    [122] = "@ASCOInvis/(AS Courtyard) Crow's Basket/",
    [123] = "@ASCO/(AS Courtyard) Ledge Above Fred Left/",
    [124] = "@ASCO/(AS Courtyard) Ledge Above Fred Right/",
    [125] = "@ASCO/(AS Courtyard) Ledge Opposite Elevator/",
    [126] = "@ASCO/(AS Courtyard) Edgar's Room/",
    [127] = "@ASCO/(AS Courtyard) Behind Elevator/",
    [128] = "@ASCO/(AS Courtyard) Junk Corner/",
    [129] = "@ASCOLev/(AS Courtyard) Above Edgar/",

    -- ASUP
    [130] = "@ASUP/(AS Upper) Behind Mattress Wall/",
    [131] = "@ASUP/(AS Upper) Checkered Bathroom/",
    [132] = "@ASUP/(AS Upper) Room Near Checkered Bathroom/",
    [133] = "@ASUP/(AS Upper) Elevator Shaft/",
    [134] = "@ASUP/(AS Upper) Room Left of Pipe Slide/",
    [135] = "@ASUP/(AS Upper) Floating in Hole/",
    [136] = "@ASUP/(AS Upper) Next to Hole/",
    [137] = "@ASUP/(AS Upper) Crumbling Outer Wall Planks/",
    [138] = "@ASUP/(AS Upper) Crumbling Outer Wall Pillar/",
    [139] = "@ASUP/(AS Upper) Crumbling Outer Wall Below Platform/",
    [140] = "@ASUPLev_optional/(AS Upper) Crumbling Outer Wall Platform/",
    [141] = "@ASUPLev_optional/(AS Upper) Room Above Tilted Stairs/",
    [142] = "@ASUPLev_optional/(AS Upper) Acid Room Floor/",
    [143] = "@ASUPLev_optional/(AS Upper) Acid Room Table/",
    [144] = "@ASUPLev_optional/(AS Upper) Acid Room Window/",
    [145] = "@ASUPLev_optional/(AS Upper) Acid Room Overhang/",
    [146] = "@ASUPLev_optional/(AS Upper) Small Windows Ledge/",
    [147] = "@ASUPLev_optional/(AS Upper) Round Wood Platform/",
    [148] = "@ASUPLev_optional/(AS Upper) Grate Climb Bottom/",
    [149] = "@ASUPLev_optional/(AS Upper) Grate Climb Mid/",
    [150] = "@ASUPLev_optional/Sink Platform/(AS Upper) Sink Platform Left",
    [151] = "@ASUPLev_optional/Sink Platform/(AS Upper) Sink Platform Right",
    [152] = "@ASUPLev/(AS Upper) Pipes Below Chair Door/",
    [153] = "@ASUPTele_optional/(AS Upper) Room Opposite Chair Door/",
    [154] = "@ASUPTele/(AS Upper) Pipe Slide Near Chair Door/",
    [155] = "@ASUPTele/(AS Upper) Rafters Above Chair Door/",

    -- ASLB
    [156] = "@ASLB/(AS Lab) Lab Caged Crow Left/",
    [157] = "@ASLB/(AS Lab) Lab Caged Crow Right/",
    [158] = "@ASLB/(AS Lab) Next to Pokeylope/",
    [159] = "@ASLB/(AS Lab) Lab Top Railing Left 1/",
    [160] = "@ASLB/(AS Lab) Lab Top Railing Left 2/",
    [161] = "@ASLB/(AS Lab) Lab Top Elevator/",
    [162] = "@ASLB/(AS Lab) Lab Top Railing Right/",
    [163] = "@ASLB/(AS Lab) Tea Room/",

    -- BB
    [164] = "@BBA1/(BB Area 1) Jumping Tutorial 1/",
    [165] = "@BBA1/(BB Area 1) Jumping Tutorial 2/",
    [166] = "@BBA1/(BB Area 1) Pole-Climbing Tutorial Floor/",
    [167] = "@BBA1/(BB Area 1) Below the Triple Trampolines/",
    [168] = "@BBA2/(BB Area 2) Giant Soldier Cut-Out/",
    [169] = "@BBA2/(BB Area 2) Dodging Bullets 1/",
    [170] = "@BBA2/(BB Area 2) Dodging Bullets 2/",
    [171] = "@BBA2/(BB Area 2) Machine Gun Turret/",
    [172] = "@BBA2/(BB Area 2) Pole-Swinging Tutorial/",
    [173] = "@BBA2Duster/(BB Area 2) Trapeze Cobweb/",
    [174] = "@BBA2/(BB Area 2) Trapeze Platform/",
    [175] = "@BBA2/(BB Area 2) Inside Plane Wreckage/",
    [176] = "@BBA2/End of Obstacle Course/(BB Finale) End of Obstacle Course Left",
    [177] = "@BBA2/End of Obstacle Course/(BB Finale) End of Obstacle Course Right",
    [178] = "@BBA2/(BB Finale) Basic Braining Complete/",

    -- BB Mental Cobwebs
    [552] = "@BBA2Cobweb/(BB Area 2 Cobweb) Trapeze Cobweb/",
    [553] = "@BBA2Cobweb/(BB Area 2 Cobweb) Tightrope Tutorial/",
    [554] = "@BBA2Cobweb/(BB Area 2 Cobweb) Grindrail Wall/",
    [555] = "@BBA2Cobweb/(BB Finale Cobweb) Bunny Room Door/",
    [556] = "@BBA2Cobweb/(BB Finale Cobweb) Tunnel of Logs End/",

    -- SA
    [179] = "@SACU/(SA Main) On the Bed/",
    [180] = "@SACU/(SA Main) On the Pillow/",
    [181] = "@SACU/Building Blocks Left/(SA Main) Building Blocks Left",
    [182] = "@SACU/Building Blocks Left/(SA Main) Building Blocks Below",
    [183] = "@SACU/(SA Main) Building Blocks Right/",
    [184] = "@SACU/(SA Main) Top of Bed Frame/",
    [185] = "@SACU/(SA Main) Round Platforms Bottom/",
    [186] = "@SACU/(SA Main) Round Platforms Near Valve/",
    [187] = "@SACULev/(SA Main) Round Platforms Far from Valve/",
    [188] = "@SACU/(SA Main) Side of Cube Face 3/",
    [189] = "@SACU/(SA Main) Bottom of Shoebox Ladder/",
    [190] = "@SACU/(SA Main) Shoebox Pedestal/",
    [191] = "@SACU/(SA Main) Shoebox Tower Top/",
    [192] = "@SACU/(SA Main) Flame Tower Steps/",
    [193] = "@SACU/(SA Main) Flame Tower Top 1/",
    [194] = "@SACU/(SA Main) Flame Tower Top 2/",
    [195] = "@SACU/(SA Main) Sasha's Shooting Gallery Complete/",

    -- SA Mental Cobwebs
    [557] = "@SACUCobweb/(SA Main Cobweb) Block Arch Left/",
    [558] = "@SACUCobweb/(SA Main Cobweb) Block Arch Right/",
    [559] = "@SACUCobweb/(SA Main Cobweb) Back of Shoebox Tower/",
    [560] = "@SACUCobweb/(SA Main Cobweb) Shoebox Tower/",
    [561] = "@SACUCobweb/(SA Main Cobweb) Flame Tower Arch/",

    -- MI
    [196] = "@MIFL/(MI Area 1) Intro Rings Tutorial/",
    [197] = "@MIFL/(MI Area 1) Dancing Camper Platform 1/",
    [198] = "@MIFL/(MI Area 1) Demon Room/",
    [199] = "@MIFL/(MI Area 1) Windy Ladder Bottom/",
    [200] = "@MIFL/(MI Area 1) Pinball Plunger/",
    [201] = "@MIFL/(MI Area 1) Plunger Party Ledge/",
    [202] = "@MIFL/(MI Area 1) Grindrail Rings/",
    [203] = "@MIFL/(MI Area 1) Censor Hallway/",
    [204] = "@MIFL/(MI Area 1) Pink Bowl Bottom/",
    [205] = "@MIFL/(MI Area 1) Pink Bowl Small Platform/",
    [206] = "@MIFL/(MI Finale) Bubbly Fan Bottom/",
    [207] = "@MIFL/(MI Finale) Bubbly Fan Platform/",
    [208] = "@MIFL/(MI Finale) Bubbly Fan Top/",
    [209] = "@MIFL/(MI Finale) Milla's Party Room/",
    [210] = "@MIFL/(MI Finale) Milla's Dance Party Complete/",

    -- MI Mental Cobwebs
    [562] = "@MIFLCobweb/(MI Area 1 Cobweb) Intro Statue Corner/",
    [563] = "@MIFLCobweb/(MI Area 1 Cobweb) Behind Pinball Ladder/",
    [564] = "@MIFLCobweb/(MI Area 1 Cobweb) Grindrail Rings/",
    [565] = "@MIFLCobweb/(MI Finale Cobweb) Fan Room Entrance/",
    [566] = "@MIFLCobweb/(MI Finale Cobweb) Party Room Floor/",

    -- BT/NI
    [211] = "@NIMP/(BT Main) Outside Caravan/",
    [212] = "@NIMP/(BT Main) Behind the Egg/",
    [213] = "@NIMP/(BT Main) Shadow Monster Path/",
    [214] = "@NIMPMark/(BT Main) Shadow Monster Blue Mushrooms/",
    [215] = "@NIMPMark/(BT Main) Ledge Behind Shadow Monster/",
    [216] = "@NIMPMark/(BT Main) Below the Steep Ledge/",
    [217] = "@NIMPMark/(BT Main) Forest Path Blue Mushrooms/",
    [218] = "@NIMPMark/(BT Main) Forest Blue Ledge/",
    [219] = "@NIMPMark/(BT Main) Forest High Platform/",
    [220] = "@NIMPMark/(BT Main) Forest Path Thorns/",
    [221] = "@NIMPMark/(BT Main) Behind Thorn Tower Left/",
    [222] = "@NIMPMark/(BT Main) Behind Thorn Tower Mid/",
    [223] = "@NIMPMark/(BT Main) Behind Thorn Tower Right/",
    [224] = "@NIBA/(BT Boss) Brain Tumbler Experiment Complete/",

    -- BT/NI Mental Cobwebs
    [567] = "@NIMPCobweb/(BT Main Cobweb) Bathtub Drain/",
    [568] = "@NIMPCobweb/(BT Main Cobweb) Forest Path Thorns/",
    [569] = "@NIMPCobweb/(BT Main Cobweb) Forest High Platform/",
    [570] = "@NIMPCobweb/(BT Main Cobweb) Shadow Monster Meat/",
    [571] = "@NIMPCobweb/(BT Main Cobweb) Thorn Tower Right/",

    -- LO
    [225] = "@LOMA/(LO Main) Skyscraper Start/",
    [226] = "@LOMA/(LO Main) Corner Near First Jail/",
    [227] = "@LOMA/(LO Main) Skyscraper before Dam/",
    [228] = "@LOMAShield/(LO Main) Behind Lasers Left 1/",
    [229] = "@LOMAShield/(LO Main) Behind Lasers Left 2/",
    [230] = "@LOMAShield/(LO Main) Behind Lasers Right/",
    [231] = "@LOMAShield/(LO Main) Blimp Hop/",
    [232] = "@LOMAShield/(LO Main) End of Dam/",
    [233] = "@LOMAShield/(LO Main) End of Dam Platform/",
    [234] = "@LOMAShield/(LO Main) Skyscraper after Dam/",
    [235] = "@LOMAShield/(LO Main) Near Battleships/",
    [236] = "@LOMAShield/(LO Main) On the Bridge/",
    [237] = "@LOMAShield/(LO Main) Ground after Bridge/",
    [238] = "@LOMAShield/(LO Main) Skyscraper after Bridge/",
    [239] = "@LOMAShield/(LO Main) Train Tunnel/",
    [240] = "@LOMAShield/(LO Main) Final Skyscrapers Left/",
    [241] = "@LOMAShield/(LO Main) Final Skyscrapers Right/",
    [242] = "@LOMAShield/(LO Boss) Kochamara Intro Left/",
    [243] = "@LOMAShield/(LO Boss) Kochamara Intro Right/",
    [244] = "@LOMAShield/(LO Boss) Lungfishopolis Complete/",

    -- LO Mental Cobwebs
    [572] = "@LOMACobweb/(LO Main Cobweb) Skyscraper Before Dam/",
    [573] = "@LOMAShieldCobweb/(LO Main Cobweb) Skyscrapers Before Tunnel/",
    [574] = "@LOMAShieldCobweb/(LO Main Cobweb) Behind Lasers/",
    [575] = "@LOMAShieldCobweb/(LO Main Cobweb) End of Dam/",
    [576] = "@LOMAShieldCobweb/(LO Main Cobweb) Ground after Bridge/",

    -- MM
    [245] = "@MMI1/(MM Neighborhood) Boyd's Fridge/",
    [246] = "@MMI1BeforeSign/(MM Neighborhood) Inside First House/",
    [247] = "@MMI1BeforeSign/(MM Neighborhood) Inside Second House/",
    [248] = "@MMI1BeforeSign/(MM Neighborhood) Car Trunk 1 (Stop Sign)/",
    [249] = "@MMI1AfterSign/(MM Neighborhood) Roof after Road Crew/",
    [250] = "@MMI1AfterSign/(MM Neighborhood) Car Trunk 2/",
    [251] = "@MMI1AfterSign/(MM Neighborhood) Car House Backyard/",
    [252] = "@MMI1Duster_optional/(MM Neighborhood) Inside Webbed Garage/",
    [253] = "@MMI1AfterSign/(MM Neighborhood) Graveyard Patio/",
    [254] = "@MMI1AfterSign/(MM Neighborhood) Graveyard Behind Tree/",
    [255] = "@MMI1AfterSign/(MM Neighborhood) Behind Graveyard/",
    [256] = "@MMI1AfterSign/(MM Neighborhood) Hedge Maze/",
    [257] = "@MMI1AfterSign/(MM Neighborhood) Car Trunk 3/",
    [258] = "@MMI1AfterSign/(MM Neighborhood) Post Office Roof/",
    [259] = "@MMI1AfterSign/(MM Neighborhood) Post Office Lobby/",
    [260] = "@MMI1Duster/(MM Neighborhood) Post Office Basement/",
    [261] = "@MMI1HedgeTrimmers/Landscapers House/(MM Neighborhood) Landscapers House Backyard",
    [262] = "@MMI1HedgeTrimmers/Landscapers House/(MM Neighborhood) Landscapers House Table",
    [263] = "@MMI1RollingPin/(MM Neighborhood) Landscapers House Kitchen/",
    [264] = "@MMI1Powerlines/(MM Neighborhood) Powerline Island Sandbox/",
    [265] = "@MMI1Powerlines/(MM Neighborhood) Powerline Island Left/",
    [266] = "@MMI1Powerlines/(MM Neighborhood) Powerline Island Right/",
    [267] = "@MMI2/(MM Depository) Behind Book Depository/",
    [268] = "@MMDM/(MM Depository) Milkman Complete/",

    -- MM Mental Cobwebs
    [577] = "@MMI1BeforeSignCobweb/(MM Neighborhood Cobweb) Third House/",
    [578] = "@MMI1AfterSignCobweb/(MM Neighborhood Cobweb) Post Office Lobby/",
    [579] = "@MMI1AfterSignCobweb/(MM Neighborhood Cobweb) Right House before Post Office/",
    [580] = "@MMI1AfterSignCobweb/(MM Neighborhood Cobweb) Webbed Garage/",
    [581] = "@MMI2Cobweb/(MM Depository Cobweb) Book Depository/",

    -- TH
    [269] = "@THMS/(TH Stage) Near the Critic/",
    [270] = "@THMSLev/(TH Stage) In the Audience/",
    [271] = "@THMS/(TH Stage) Below the Spotlight/",
    [272] = "@THMS/(TH Stage) Behind Stage/",
    [273] = "@THMSDuster_optional/(TH Stage) Behind Stage Cobweb/",
    [274] = "@THMSStorage/(TH Stage) Storage Room Floor/",
    [275] = "@THMSStorage/(TH Stage) Storage Room Left/",
    [276] = "@THMSStorage/Storage Room Right/(TH Stage) Storage Room Right Lower",
    [277] = "@THMSStorage/Storage Room Right/(TH Stage) Storage Room Right Upper",
    [278] = "@THMSBonita/(TH Stage) Bonita's Room/",
    [279] = "@THCW/(TH Catwalks) Doghouse Slicers/",
    [280] = "@THCW/(TH Catwalks) Big Platform 1/",
    [281] = "@THCW/(TH Catwalks) Big Platform 2/",
    [282] = "@THCW/Big Platform Corner/(TH Catwalks) Big Platform 3",
    [283] = "@THCW/Big Platform Corner/(TH Catwalks) Big Platform Above",
    [284] = "@THCW/(TH Catwalks) Next to Oatmeal/",
    [285] = "@THCW/(TH Catwalks) Candle Basket/",
    [286] = "@THCW/(TH Catwalks) Curtain Slide/",
    [287] = "@THFB/(TH Catwalks) Gloria's Theater Complete/",

    -- TH Mental Cobwebs
    [582] = "@THMSCobweb/(TH Stage Cobweb) Backstage Corridor/",
    [583] = "@THMSCobweb/(TH Stage Cobweb) Below Teleporter/",
    [584] = "@THMSStorageCobweb/(TH Stage Cobweb) Storage Room Left/",
    [585] = "@THMSLevCobweb/(TH Stage Cobweb) In the Audience/",
    [586] = "@THMSCobweb/(TH Stage Cobweb) Below the Critic/",
    [587] = "@THMSCobweb/(TH Stage Cobweb) Behind Stage/",
    [588] = "@THMSStorageCobweb/(TH Stage Cobweb) Storage Room Right/",

    -- WW
    [288] = "@WWMA/(WW Main) Fred's Room/",
    [289] = "@WWMA/(WW Main) The Fireplace/",
    [290] = "@WWMA/(WW Main) Game Board/",
    [291] = "@WWMACarpRoof/(WW Main) Carpenter's Roof/",
    [292] = "@WWMACarpRoof/(WW Main) Tightrope Room/",
    [293] = "@WWMA/(WW Main) Outside Villager 1 House/",
    [294] = "@WWMA/(WW Main) Small Arch Top/",
    [295] = "@WWMA/(WW Main) Small Arch Below/",
    [296] = "@WWMA/(WW Main) Top of Villager 2's House/",
    [297] = "@WWMALev/(WW Main) Top of Villager 3's House/",
    [298] = "@WWMALev/(WW Main) Top of Knight's House/",
    [299] = "@WWMA/(WW Main) Castle Tower/",
    [300] = "@WWMA/(WW Main) Castle Inside/",
    [301] = "@WWMA/(WW Main) Castle Wall/",
    [302] = "@WWMADuster/(WW Main) Under the Guillotine/",
    [303] = "@WWMADuster/(WW Main) Fred's House Basement/",
    [304] = "@WWMABlacksmithLeft/(WW Main) Blacksmith's Left Building/",
    [305] = "@WWMABlacksmithRight/(WW Main) Blacksmith's Right Building/",
    [306] = "@WWMADusterLevPyro/(WW Main) Blacksmith's Haybale/",
    [307] = "@WWMA/(WW Main) Help the Carpenter/",
    [308] = "@WWMAV1/(WW Main) Help Villager 1/",
    [309] = "@WWMAKnight/(WW Main) Help the Knight/",
    [310] = "@WWMAV2/(WW Main) Help Villager 2/",
    [311] = "@WWMAV3/(WW Main) Help Villager 3/",
    [312] = "@WWMADone/(WW Main) Waterloo World Complete/",

    -- WW Mental Cobwebs
    [589] = "@WWMACobweb/(WW Main Cobweb) Beneath Small Arch/",
    [590] = "@WWMACobweb/(WW Main Cobweb) Blacksmith's Right Building Window/",
    [591] = "@WWMACobweb/(WW Main Cobweb) Blacksmith's Left Building/",
    [592] = "@WWMABlacksmithRightCobweb/(WW Main Cobweb) Blacksmith's Right Building Roof/",
    [593] = "@WWMACobweb/(WW Main Cobweb) Carpenter's House/",
    [594] = "@WWMACobweb/(WW Main Cobweb) Fred's House Basement/",
    [595] = "@WWMACobweb/(WW Main Cobweb) Under the Guillotine/",

    -- BV
    [313] = "@BVRB/(BV Streets) Club Street Lady/",
    [314] = "@BVRBLev_optional/(BV Streets) Club Street Metal Balcony/",
    [315] = "@BVRBLev/(BV Streets) Heart Street HIGH Balcony/",
    [316] = "@BVRB/(BV Streets) Alleyways Ledge/",
    [317] = "@BVRB/(BV Streets) Sewers Main/",
    [318] = "@BVRBTele/(BV Streets) Club Street Gated/",
    [319] = "@BVRBLogs/(BV Streets) Burn the Logs/",
    [320] = "@BVRBTele/(BV Streets) The Garden/",
    [321] = "@BVRB/(BV Streets) Near Diego's House/",
    [322] = "@BVRBDuster/(BV Streets) Diego's Bed/",
    [323] = "@BVRBDuster_optional/(BV Streets) Diego's House Grindrail/",
    [324] = "@BVRBDuster/(BV Streets) Diego's Room/",
    [325] = "@BVRBDuster_optional/(BV Streets) Grindrail Balcony/",
    [326] = "@BVESLev/(BV Edgar) Sanctuary Balcony/",
    [327] = "@BVES/(BV Edgar) Sanctuary Ground/",
    [328] = "@BVES/(BV Edgar) Tiger Wrestler/",
    [329] = "@BVES/(BV Edgar) Dragon Wrestler/",
    [330] = "@BVES/(BV Edgar) Eagle Wrestler/",
    [331] = "@BVESCobra/(BV Edgar) Cobra Wrestler/",
    [332] = "@BVESBoss/(BV Edgar) Black Velvetopia Complete/",

    -- BV Mental Cobwebs
    [596] = "@BVRBDusterCobweb/(BV Streets Cobweb) Diego's House Grindrail/",
    [597] = "@BVRBCobweb/(BV Streets Cobweb) Diego's House/",
    [598] = "@BVRBCobweb/(BV Streets Cobweb) Sewer Shower Tunnel/",
    [599] = "@BVRBCobweb/(BV Streets Cobweb) Above Queen of Hearts/",
    [600] = "@BVRBCobweb/(BV Streets Cobweb) Sewer Before Gate/",
    [601] = "@BVRBDusterCobweb/(BV Streets Cobweb) Diego's House Fireplace/",
    [602] = "@BVRBCobweb/(BV Streets Cobweb) Near Diego's House/",

    -- MC
    [333] = "@MCTCLev/(MC Main) Entrance Awning/",
    [334] = "@MCTC/(MC Main) Crumbling Path/",
    [335] = "@MCTC/(MC Main) Crumbling Path End Right/",
    [336] = "@MCTC/(MC Main) Crumbling Path End Left/",
    [337] = "@MCTC/(MC Main) Ollie Escort Floor/",
    [338] = "@MCTCEscort/(MC Main) Ollie Escort Middle/",
    [339] = "@MCTCEscortTop/Ollie Escort Top/(MC Main) Ollie Escort Top Left",
    [340] = "@MCTCEscortTop/Ollie Escort Top/(MC Main) Ollie Escort Top Right",
    [341] = "@MCTCToL/(MC Main) Tunnel of Love Start/",
    [342] = "@MCTCToL/(MC Main) Tunnel of Love Corner/",
    [343] = "@MCTCToL/(MC Main) Tunnel of Love Rail/",
    [344] = "@MCTCToL/(MC Main) Next to the Final Door/",

    -- MC Mental Cobwebs
    [603] = "@MCTCToLCobweb/(MC Main Cobweb) Tunnel of Love Ollie Escort Exit/",
    [604] = "@MCTCCobweb/(MC Main Cobweb) Entrance Hall/",
    [605] = "@MCTCCobweb/(MC Main Cobweb) Entrance Hall/",

    -- Figment Percentage Locations
    [706] = "@BB Figments/(BB Figments) Collect Figments 20 Percent",
    [707] = "@SA Figments/(SA Figments) Collect Figments 20 Percent",
    [708] = "@MI Figments/(MI Figments) Collect Figments 20 Percent",
    [709] = "@BT Figments/(BT Figments) Collect Figments 20 Percent",
    [710] = "@LO Figments/(LO Figments) Collect Figments 20 Percent",
    [711] = "@MM Figments/(MM Figments) Collect Figments 20 Percent",
    [712] = "@TH Figments/(TH Figments) Collect Figments 20 Percent",
    [713] = "@WW Figments/(WW Figments) Collect Figments 20 Percent",
    [714] = "@BV Figments/(BV Figments) Collect Figments 20 Percent",
    [715] = "@MC Figments/(MC Figments) Collect Figments 20 Percent",

    [716] = "@BB Figments/(BB Figments) Collect Figments 40 Percent",
    [717] = "@SA Figments/(SA Figments) Collect Figments 40 Percent",
    [718] = "@MI Figments/(MI Figments) Collect Figments 40 Percent",
    [719] = "@BT Figments/(BT Figments) Collect Figments 40 Percent",
    [720] = "@LO Figments/(LO Figments) Collect Figments 40 Percent",
    [721] = "@MM Figments/(MM Figments) Collect Figments 40 Percent",
    [722] = "@TH Figments/(TH Figments) Collect Figments 40 Percent",
    [723] = "@WW Figments/(WW Figments) Collect Figments 40 Percent",
    [724] = "@BV Figments/(BV Figments) Collect Figments 40 Percent",
    [725] = "@MC Figments/(MC Figments) Collect Figments 40 Percent",

    [726] = "@BB Figments/(BB Figments) Collect Figments 60 Percent",
    [727] = "@SA Figments/(SA Figments) Collect Figments 60 Percent",
    [728] = "@MI Figments/(MI Figments) Collect Figments 60 Percent",
    [729] = "@BT Figments/(BT Figments) Collect Figments 60 Percent",
    [730] = "@LO Figments/(LO Figments) Collect Figments 60 Percent",
    [731] = "@MM Figments/(MM Figments) Collect Figments 60 Percent",
    [732] = "@TH Figments/(TH Figments) Collect Figments 60 Percent",
    [733] = "@WW Figments/(WW Figments) Collect Figments 60 Percent",
    [734] = "@BV Figments/(BV Figments) Collect Figments 60 Percent",
    [735] = "@MC Figments/(MC Figments) Collect Figments 60 Percent",

    [736] = "@BB Figments/(BB Figments) Collect Figments 80 Percent",
    [737] = "@SA Figments/(SA Figments) Collect Figments 80 Percent",
    [738] = "@MI Figments/(MI Figments) Collect Figments 80 Percent",
    [739] = "@BT Figments/(BT Figments) Collect Figments 80 Percent",
    [740] = "@LO Figments/(LO Figments) Collect Figments 80 Percent",
    [741] = "@MM Figments/(MM Figments) Collect Figments 80 Percent",
    [742] = "@TH Figments/(TH Figments) Collect Figments 80 Percent",
    [743] = "@WW Figments/(WW Figments) Collect Figments 80 Percent",
    [744] = "@BV Figments/(BV Figments) Collect Figments 80 Percent",
    [745] = "@MC Figments/(MC Figments) Collect Figments 80 Percent",

    [746] = "@BB Figments/(BB Figments) Collect Figments 100 Percent",
    [747] = "@SA Figments/(SA Figments) Collect Figments 100 Percent",
    [748] = "@MI Figments/(MI Figments) Collect Figments 100 Percent",
    [749] = "@BT Figments/(BT Figments) Collect Figments 100 Percent",
    [750] = "@LO Figments/(LO Figments) Collect Figments 100 Percent",
    [751] = "@MM Figments/(MM Figments) Collect Figments 100 Percent",
    [752] = "@TH Figments/(TH Figments) Collect Figments 100 Percent",
    [753] = "@WW Figments/(WW Figments) Collect Figments 100 Percent",
    [754] = "@BV Figments/(BV Figments) Collect Figments 100 Percent",
    [755] = "@MC Figments/(MC Figments) Collect Figments 100 Percent",

    -- Progressive Baggage
    [756] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 1",
    [757] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 2",
    [758] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 3",
    [759] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 4",
    [760] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 5",
    [761] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 6",
    [762] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 7",
    [763] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 8",
    [764] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 9",
    [765] = "@Progressive Suitcase/(Baggage) Suitcase Redeemed 10",
    [766] = "@Progressive Purse/(Baggage) Purse Redeemed 1",
    [767] = "@Progressive Purse/(Baggage) Purse Redeemed 2",
    [768] = "@Progressive Purse/(Baggage) Purse Redeemed 3",
    [769] = "@Progressive Purse/(Baggage) Purse Redeemed 4",
    [770] = "@Progressive Purse/(Baggage) Purse Redeemed 5",
    [771] = "@Progressive Purse/(Baggage) Purse Redeemed 6",
    [772] = "@Progressive Purse/(Baggage) Purse Redeemed 7",
    [773] = "@Progressive Purse/(Baggage) Purse Redeemed 8",
    [774] = "@Progressive Purse/(Baggage) Purse Redeemed 9",
    [775] = "@Progressive Purse/(Baggage) Purse Redeemed 10",
    [776] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 1",
    [777] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 2",
    [778] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 3",
    [779] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 4",
    [780] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 5",
    [781] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 6",
    [782] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 7",
    [783] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 8",
    [784] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 9",
    [785] = "@Progressive Hatbox/(Baggage) Hatbox Redeemed 10",
    [786] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 1",
    [787] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 2",
    [788] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 3",
    [789] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 4",
    [790] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 5",
    [791] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 6",
    [792] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 7",
    [793] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 8",
    [794] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 9",
    [795] = "@Progressive Steamertrunk/(Baggage) Steamertrunk Redeemed 10",
    [796] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 1",
    [797] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 2",
    [798] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 3",
    [799] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 4",
    [800] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 5",
    [801] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 6",
    [802] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 7",
    [803] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 8",
    [804] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 9",
    [805] = "@Progressive Dufflebag/(Baggage) Dufflebag Redeemed 10",

    -- Events (goals)
    -- Note: These locations do not currently get sent upon completing them.
    [500] = "@MCTCBoss/Goal - Meat Circus Bosses/(MC Boss) Final Boss Defeated (no item)",
    [501] = "@CAJABrains/Goal - Brain Hunt/(CA Ford) Redeemed Required Brains (no item)",
    [502] = "@ASLBBoss/Goal - Asylum Brain Tank/(AS Lab) Oleander Boss Defeated (no item)",
}